#############################################################################
# Makefile for building: BciSift
# Generated by qmake (3.1) (Qt 5.12.0)
# Project:  BciSift.pro
# Template: app
# Command: /Users/rramele/Qt/5.12.0/clang_64/bin/qmake -o Makefile BciSift.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.9 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1y $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.9 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../opencv/include -I/usr/local/include -I../kfr/include -I../labstreaminglayer/build/install/LSL/include -I../vlfeat -I../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers -I. -I../../Qt/5.12.0/clang_64/mkspecs/macx-clang -F/Users/rramele/Qt/5.12.0/clang_64/lib
QMAKE         = /Users/rramele/Qt/5.12.0/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/rramele/Qt/5.12.0/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/rramele/Qt/5.12.0/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = BciSift1.0.0
DISTDIR = /Users/rramele/work/BciSift/.tmp/BciSift1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.9 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/rramele/Qt/5.12.0/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/rramele/Qt/5.12.0/clang_64/lib -L/usr/local/lib -L/Users/rramele/work/labstreaminglayer/build/install/LSL/lib/ -L/Users/rramele/work/vlfeat/bin/maci64/ -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_features2d -lopencv_xfeatures2d -lopencv_calib3d -lopencv_imgcodecs -lopencv_ml -lopencv_flann -llsl64 -lvl -framework QtCore -framework DiskArbitration -framework IOKit   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		eegimage.cpp \
		scalespace.cpp \
		plotprocessing.cpp \
		dsp.cpp \
		lsl.cpp \
		lsltransmitter.cpp \
		decoder.cpp \
		serializer.cpp \
		unp.cpp 
OBJECTS       = main.o \
		eegimage.o \
		scalespace.o \
		plotprocessing.o \
		dsp.o \
		lsl.o \
		lsltransmitter.o \
		decoder.o \
		serializer.o \
		unp.o
DIST          = ../../Qt/5.12.0/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.12.0/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.12.0/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.12.0/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.12.0/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.12.0/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.12.0/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.12.0/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.12.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.12.0/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.12.0/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.12.0/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.12.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.12.0/clang_64/mkspecs/features/spec_post.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/toolchain.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/mac/mac.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/lex.prf \
		BciSift.pro eegimage.h \
		plotprocessing.h \
		dsp.h \
		lsl.h \
		decoder.h \
		serializer.h \
		unp.h \
		spellerletter.h main.cpp \
		eegimage.cpp \
		scalespace.cpp \
		plotprocessing.cpp \
		dsp.cpp \
		lsl.cpp \
		lsltransmitter.cpp \
		decoder.cpp \
		serializer.cpp \
		unp.cpp
QMAKE_TARGET  = BciSift
DESTDIR       = 
TARGET        = BciSift

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx10.14
EXPORT_QMAKE_MAC_SDK_VERSION = 10.14
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


include /Users/rramele/Qt/5.12.0/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

BciSift:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: BciSift.pro ../../Qt/5.12.0/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.12.0/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.12.0/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.12.0/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.12.0/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.12.0/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.12.0/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.12.0/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.12.0/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.12.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.12.0/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.12.0/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.12.0/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.12.0/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.12.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.12.0/clang_64/mkspecs/features/spec_post.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/toolchain.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/mac/mac.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.12.0/clang_64/mkspecs/features/lex.prf \
		BciSift.pro \
		../../Qt/5.12.0/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile BciSift.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../Qt/5.12.0/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.12.0/clang_64/mkspecs/qdevice.pri:
../../Qt/5.12.0/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.12.0/clang_64/mkspecs/common/unix.conf:
../../Qt/5.12.0/clang_64/mkspecs/common/mac.conf:
../../Qt/5.12.0/clang_64/mkspecs/common/macx.conf:
../../Qt/5.12.0/clang_64/mkspecs/common/sanitize.conf:
../../Qt/5.12.0/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.12.0/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.12.0/clang_64/mkspecs/common/clang.conf:
../../Qt/5.12.0/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.12.0/clang_64/mkspecs/qconfig.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.12.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.12.0/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.12.0/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.12.0/clang_64/mkspecs/features/spec_post.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/toolchain.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/mac/toolchain.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/qml_debug.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/mac/mac.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/qt.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/resources.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/moc.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/qmake_use.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/file_copies.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.12.0/clang_64/mkspecs/features/lex.prf:
BciSift.pro:
../../Qt/5.12.0/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile BciSift.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile BciSift

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt/5.12.0/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents eegimage.h plotprocessing.h dsp.h lsl.h decoder.h serializer.h unp.h spellerletter.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp eegimage.cpp scalespace.cpp plotprocessing.cpp dsp.cpp lsl.cpp lsltransmitter.cpp decoder.cpp serializer.cpp unp.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt/5.12.0/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++1y $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.9 -Wall -W -dM -E -o moc_predefs.h ../../Qt/5.12.0/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp ../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QGlobal.h \
		../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QTime \
		../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		eegimage.h \
		lsl.h \
		plotprocessing.h \
		spellerletter.h \
		decoder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

eegimage.o: eegimage.cpp /usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QGlobal.h \
		../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QTime \
		../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../vlfeat/vl/sift.h \
		../vlfeat/vl/generic.h \
		../vlfeat/vl/host.h \
		../vlfeat/vl/random.h \
		../vlfeat/vl/mathop.h \
		bcisift.cpp \
		/usr/local/include/opencv2/xfeatures2d.hpp \
		/usr/local/include/opencv2/xfeatures2d/nonfree.hpp \
		plotprocessing.h \
		spellerletter.h \
		dsp.h \
		lsl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eegimage.o eegimage.cpp

scalespace.o: scalespace.cpp /usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/xfeatures2d.hpp \
		/usr/local/include/opencv2/xfeatures2d/nonfree.hpp \
		../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QGlobal.h \
		../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QTime \
		../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qdatetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scalespace.o scalespace.cpp

plotprocessing.o: plotprocessing.cpp /usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/xfeatures2d.hpp \
		/usr/local/include/opencv2/xfeatures2d/nonfree.hpp \
		/usr/local/include/opencv2/ml.hpp \
		../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QGlobal.h \
		../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/QTime \
		../../Qt/5.12.0/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		serializer.h \
		../opencv/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/calib3d/calib3d_c.h \
		/usr/local/include/opencv2/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		../vlfeat/vl/random.h \
		../vlfeat/vl/host.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/shape.hpp \
		/usr/local/include/opencv2/shape/emdL1.hpp \
		/usr/local/include/opencv2/shape/shape_transformer.hpp \
		/usr/local/include/opencv2/shape/hist_cost.hpp \
		/usr/local/include/opencv2/shape/shape_distance.hpp \
		/usr/local/include/opencv2/stitching.hpp \
		/usr/local/include/opencv2/stitching/warpers.hpp \
		/usr/local/include/opencv2/stitching/detail/warpers.hpp \
		/usr/local/include/opencv2/core/cuda.hpp \
		/usr/local/include/opencv2/core/cuda_types.hpp \
		/usr/local/include/opencv2/core/cuda.inl.hpp \
		/usr/local/include/opencv2/stitching/detail/warpers_inl.hpp \
		/usr/local/include/opencv2/stitching/detail/matchers.hpp \
		/usr/local/include/opencv2/xfeatures2d/cuda.hpp \
		/usr/local/include/opencv2/stitching/detail/motion_estimators.hpp \
		/usr/local/include/opencv2/stitching/detail/util.hpp \
		/usr/local/include/opencv2/stitching/detail/util_inl.hpp \
		/usr/local/include/opencv2/stitching/detail/camera.hpp \
		/usr/local/include/opencv2/stitching/detail/exposure_compensate.hpp \
		/usr/local/include/opencv2/stitching/detail/seam_finders.hpp \
		/usr/local/include/opencv2/stitching/detail/blenders.hpp \
		/usr/local/include/opencv2/superres.hpp \
		/usr/local/include/opencv2/superres/optical_flow.hpp \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/video/tracking_c.h \
		/usr/local/include/opencv2/videostab.hpp \
		/usr/local/include/opencv2/videostab/stabilizer.hpp \
		/usr/local/include/opencv2/videostab/global_motion.hpp \
		/usr/local/include/opencv2/videostab/optical_flow.hpp \
		/usr/local/include/opencv2/videostab/motion_core.hpp \
		/usr/local/include/opencv2/videostab/outlier_rejection.hpp \
		/usr/local/include/opencv2/videostab/motion_stabilizing.hpp \
		/usr/local/include/opencv2/videostab/frame_source.hpp \
		/usr/local/include/opencv2/videostab/log.hpp \
		/usr/local/include/opencv2/videostab/inpainting.hpp \
		/usr/local/include/opencv2/videostab/fast_marching.hpp \
		/usr/local/include/opencv2/videostab/fast_marching_inl.hpp \
		/usr/local/include/opencv2/videostab/deblurring.hpp \
		/usr/local/include/opencv2/videostab/wobble_suppression.hpp \
		/usr/local/include/opencv2/videostab/ring_buffer.hpp \
		spellerletter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plotprocessing.o plotprocessing.cpp

dsp.o: dsp.cpp ../kfr/include/kfr/base.hpp \
		../kfr/include/kfr/base/abs.hpp \
		../kfr/include/kfr/base/function.hpp \
		../kfr/include/kfr/base/expression.hpp \
		../kfr/include/kfr/base/platform.hpp \
		../kfr/include/kfr/base/types.hpp \
		../kfr/include/kfr/base/kfr.h \
		../kfr/include/kfr/cident.h \
		../kfr/include/kfr/base/intrinsics.h \
		../kfr/include/kfr/testo/testo.hpp \
		../kfr/include/kfr/testo/comparison.hpp \
		../kfr/include/kfr/cometa/tuple.hpp \
		../kfr/include/kfr/cometa.hpp \
		../kfr/include/kfr/cometa/range.hpp \
		../kfr/include/kfr/cometa/string.hpp \
		../kfr/include/kfr/cometa/cstring.hpp \
		../kfr/include/kfr/cometa/ctti.hpp \
		../kfr/include/kfr/cometa/named_arg.hpp \
		../kfr/include/kfr/ext/console_colors.hpp \
		../kfr/include/kfr/base/vec.hpp \
		../kfr/include/kfr/base/constants.hpp \
		../kfr/include/kfr/base/simd_clang.hpp \
		../kfr/include/kfr/base/simd_intrin.hpp \
		../kfr/include/kfr/base/simd_x86.hpp \
		../kfr/include/kfr/base/shuffle.hpp \
		../kfr/include/kfr/base/specializations.i \
		../kfr/include/kfr/base/operators.hpp \
		../kfr/include/kfr/base/bitwise.hpp \
		../kfr/include/kfr/base/select.hpp \
		../kfr/include/kfr/base/asin_acos.hpp \
		../kfr/include/kfr/base/atan.hpp \
		../kfr/include/kfr/base/sin_cos.hpp \
		../kfr/include/kfr/base/min_max.hpp \
		../kfr/include/kfr/base/round.hpp \
		../kfr/include/kfr/base/sqrt.hpp \
		../kfr/include/kfr/base/basic_expressions.hpp \
		../kfr/include/kfr/base/univector.hpp \
		../kfr/include/kfr/cometa/array.hpp \
		../kfr/include/kfr/base/memory.hpp \
		../kfr/include/kfr/base/read_write.hpp \
		../kfr/include/kfr/base/clamp.hpp \
		../kfr/include/kfr/base/comparison.hpp \
		../kfr/include/kfr/base/compiletime.hpp \
		../kfr/include/kfr/base/complex.hpp \
		../kfr/include/kfr/base/hyperbolic.hpp \
		../kfr/include/kfr/base/log_exp.hpp \
		../kfr/include/kfr/base/digitreverse.hpp \
		../kfr/include/kfr/base/filter.hpp \
		../kfr/include/kfr/base/pointer.hpp \
		../kfr/include/kfr/base/gamma.hpp \
		../kfr/include/kfr/base/generators.hpp \
		../kfr/include/kfr/base/horizontal.hpp \
		../kfr/include/kfr/base/logical.hpp \
		../kfr/include/kfr/base/modzerobessel.hpp \
		../kfr/include/kfr/base/random.hpp \
		../kfr/include/kfr/base/reduce.hpp \
		../kfr/include/kfr/base/saturation.hpp \
		../kfr/include/kfr/base/small_buffer.hpp \
		../kfr/include/kfr/base/sort.hpp \
		../kfr/include/kfr/base/tan.hpp \
		../kfr/include/kfr/version.hpp \
		../kfr/include/kfr/dft.hpp \
		../kfr/include/kfr/dft/bitrev.hpp \
		../kfr/include/kfr/data/bitrev.hpp \
		../kfr/include/kfr/dft/ft.hpp \
		../kfr/include/kfr/data/sincos.hpp \
		../kfr/include/kfr/dft/convolution.hpp \
		../kfr/include/kfr/dft/cache.hpp \
		../kfr/include/kfr/dft/fft.hpp \
		../kfr/include/kfr/dft/reference_dft.hpp \
		../kfr/include/kfr/dsp.hpp \
		../kfr/include/kfr/dsp/biquad.hpp \
		../kfr/include/kfr/dsp/biquad_design.hpp \
		../kfr/include/kfr/dsp/dcremove.hpp \
		../kfr/include/kfr/dsp/delay.hpp \
		../kfr/include/kfr/dsp/ebu.hpp \
		../kfr/include/kfr/testo/assert.hpp \
		../kfr/include/kfr/dsp/speaker.hpp \
		../kfr/include/kfr/dsp/units.hpp \
		../kfr/include/kfr/dsp/fir.hpp \
		../kfr/include/kfr/dsp/fir_design.hpp \
		../kfr/include/kfr/dsp/fracdelay.hpp \
		../kfr/include/kfr/dsp/goertzel.hpp \
		../kfr/include/kfr/dsp/interpolation.hpp \
		../kfr/include/kfr/dsp/mixdown.hpp \
		../kfr/include/kfr/dsp/oscillators.hpp \
		../kfr/include/kfr/dsp/sample_rate_conversion.hpp \
		../kfr/include/kfr/dsp/window.hpp \
		../kfr/include/kfr/dsp/special.hpp \
		../kfr/include/kfr/dsp/waveshaper.hpp \
		../kfr/include/kfr/dsp/weighting.hpp \
		../kfr/include/kfr/io.hpp \
		../kfr/include/kfr/io/audiofile.hpp \
		../kfr/include/kfr/io/file.hpp \
		../kfr/include/kfr/io/python_plot.hpp \
		../kfr/include/kfr/io/tostring.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dsp.o dsp.cpp

lsl.o: lsl.cpp ../labstreaminglayer/build/install/LSL/include/lsl_cpp.h \
		../labstreaminglayer/build/install/LSL/include/lsl_c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lsl.o lsl.cpp

lsltransmitter.o: lsltransmitter.cpp ../labstreaminglayer/build/install/LSL/include/lsl_cpp.h \
		../labstreaminglayer/build/install/LSL/include/lsl_c.h \
		eegimage.h \
		plotprocessing.h \
		spellerletter.h \
		unp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lsltransmitter.o lsltransmitter.cpp

decoder.o: decoder.cpp /usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/ml.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o decoder.o decoder.cpp

serializer.o: serializer.cpp ../opencv/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/opencv_modules.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/hal/interface.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/neon_utils.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/saturate.hpp \
		/usr/local/include/opencv2/core/fast_math.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/core/ovx.hpp \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/calib3d/calib3d_c.h \
		/usr/local/include/opencv2/flann.hpp \
		/usr/local/include/opencv2/flann/flann_base.hpp \
		/usr/local/include/opencv2/flann/general.h \
		/usr/local/include/opencv2/flann/matrix.h \
		/usr/local/include/opencv2/flann/params.h \
		/usr/local/include/opencv2/flann/any.h \
		/usr/local/include/opencv2/flann/saving.h \
		/usr/local/include/opencv2/flann/nn_index.h \
		/usr/local/include/opencv2/flann/result_set.h \
		/usr/local/include/opencv2/flann/all_indices.h \
		/usr/local/include/opencv2/flann/kdtree_index.h \
		/usr/local/include/opencv2/flann/dynamic_bitset.h \
		/usr/local/include/opencv2/flann/dist.h \
		/usr/local/include/opencv2/flann/heap.h \
		/usr/local/include/opencv2/flann/allocator.h \
		../vlfeat/vl/random.h \
		../vlfeat/vl/host.h \
		/usr/local/include/opencv2/flann/kdtree_single_index.h \
		/usr/local/include/opencv2/flann/kmeans_index.h \
		/usr/local/include/opencv2/flann/logger.h \
		/usr/local/include/opencv2/flann/composite_index.h \
		/usr/local/include/opencv2/flann/linear_index.h \
		/usr/local/include/opencv2/flann/hierarchical_clustering_index.h \
		/usr/local/include/opencv2/flann/lsh_index.h \
		/usr/local/include/opencv2/flann/lsh_table.h \
		/usr/local/include/opencv2/flann/autotuned_index.h \
		/usr/local/include/opencv2/flann/ground_truth.h \
		/usr/local/include/opencv2/flann/index_testing.h \
		/usr/local/include/opencv2/flann/timer.h \
		/usr/local/include/opencv2/flann/sampling.h \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/include/opencv2/videoio/videoio_c.h \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/ml.hpp \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/objdetect/objdetect_c.h \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/shape.hpp \
		/usr/local/include/opencv2/shape/emdL1.hpp \
		/usr/local/include/opencv2/shape/shape_transformer.hpp \
		/usr/local/include/opencv2/shape/hist_cost.hpp \
		/usr/local/include/opencv2/shape/shape_distance.hpp \
		/usr/local/include/opencv2/stitching.hpp \
		/usr/local/include/opencv2/stitching/warpers.hpp \
		/usr/local/include/opencv2/stitching/detail/warpers.hpp \
		/usr/local/include/opencv2/core/cuda.hpp \
		/usr/local/include/opencv2/core/cuda_types.hpp \
		/usr/local/include/opencv2/core/cuda.inl.hpp \
		/usr/local/include/opencv2/stitching/detail/warpers_inl.hpp \
		/usr/local/include/opencv2/stitching/detail/matchers.hpp \
		/usr/local/include/opencv2/xfeatures2d/cuda.hpp \
		/usr/local/include/opencv2/stitching/detail/motion_estimators.hpp \
		/usr/local/include/opencv2/stitching/detail/util.hpp \
		/usr/local/include/opencv2/stitching/detail/util_inl.hpp \
		/usr/local/include/opencv2/stitching/detail/camera.hpp \
		/usr/local/include/opencv2/stitching/detail/exposure_compensate.hpp \
		/usr/local/include/opencv2/stitching/detail/seam_finders.hpp \
		/usr/local/include/opencv2/stitching/detail/blenders.hpp \
		/usr/local/include/opencv2/superres.hpp \
		/usr/local/include/opencv2/superres/optical_flow.hpp \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/video/tracking_c.h \
		/usr/local/include/opencv2/videostab.hpp \
		/usr/local/include/opencv2/videostab/stabilizer.hpp \
		/usr/local/include/opencv2/videostab/global_motion.hpp \
		/usr/local/include/opencv2/videostab/optical_flow.hpp \
		/usr/local/include/opencv2/videostab/motion_core.hpp \
		/usr/local/include/opencv2/videostab/outlier_rejection.hpp \
		/usr/local/include/opencv2/videostab/motion_stabilizing.hpp \
		/usr/local/include/opencv2/videostab/frame_source.hpp \
		/usr/local/include/opencv2/videostab/log.hpp \
		/usr/local/include/opencv2/videostab/inpainting.hpp \
		/usr/local/include/opencv2/videostab/fast_marching.hpp \
		/usr/local/include/opencv2/videostab/fast_marching_inl.hpp \
		/usr/local/include/opencv2/videostab/deblurring.hpp \
		/usr/local/include/opencv2/videostab/wobble_suppression.hpp \
		/usr/local/include/opencv2/videostab/ring_buffer.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serializer.o serializer.cpp

unp.o: unp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unp.o unp.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

